[Feat/#14] 제품 Entity, 기본기능 (제품 등록, 모두 조회, 이름으로 조회) API
beyond-sw-camp/be08-fin-3Dasoo-SalesBoost pull request #29
Opened 2024-09-29 11:32 UTC by leejijung

## 📢 작업 내용 설명
> 제품 엔티티 작성 및 단순 조회 등록 api 작성
<br>

<details>
  <summary> 스크린샷(선택) </summary>

</details>

<br>

## #️⃣연관된  issue
#이슈번호

<br>

## ✅ 체크리스트
- [x ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 코드 중간 통합

<br>

## 📑To Reviewers (선택)

- 리뷰어가 특별히 봐주었으면 하는 부분

2024-09-29 12:17 UTC, kuk329 commented
클래스 단에 @RestController 붙이면 각 메소드에 @ResponseBody 는 안붙혀도 됩니다.  🧐

2024-09-29 12:30 UTC, uzz99 requested changes
코드 리뷰 확인해주세요

2024-09-29 12:30 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/entity/Product.java
> +    private String name;            // 제품명
컬럼 정의 안 해놓은 이유가 있는건가요
그리고 estimate 엔티티 올라온거 있으니까 `@OneToMany`로 매핑도 해주십쇼

2024-09-29 12:30 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
> +                .map(product -> new ProductResponseDto(
그냥 참고) 엔티티에 빌더 패턴 썼으니까 여기도 빌더로 객체 생성해도 될듯합니다

2024-09-29 12:30 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
> +        return null;
null 반환보단 예외던지는게 나을 것 같습니다
공통 예외 처리(`BaseException`, `BaseResponseStatus`) 올라온거 있으니까 확인 후 변경해주시면 될 것 같아요

2024-09-29 12:30 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
> +            return productRepository.findByName(name);
불필요한 조회가 두번 일어나고 있습니다
예외를 던지는 방식으로 처리하거나 옵셔널 쓰는게 나을 것 같습니다
`existsByName` 조건문 없애고
            `return productRepository.findByName(name);` 하나만 써주십쇼

2024-09-29 12:33 UTC, uzz99 commented
다음부터는
1. 커밋 메세지 작성 시 대괄호 없애기 `feat: #14 제품 Entity, 기본기능 (제품 등록, 모두 조회, 이름으로 조회) API`

2. 옆에 라벨이랑 담당자도 달아주세요

![image](https://github.com/user-attachments/assets/a2ffbcb6-0027-4bad-844b-8f4a5bedc87f)

3. 관련 이슈번호도 작성해주시면 됩니다

![image](https://github.com/user-attachments/assets/a5d7cb57-3994-44cc-96e8-cb40a07cb0e5)

2024-09-30 03:41 UTC, uzz99 requested changes

2024-09-30 03:41 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/entity/Product.java
> +    private int quantity;           // 포장 수량
```
@Column(nullable = false)
    private int quantity;   
```
null을 허용하는 정수값들은 Integer로 변경하는게 적합합니다
안그러면 값이 존재하지 않을 때 에러가 발생합니다..
int에 기본값을 설정해주거나
```
    private Integer quantity;   
```
로 변경해주십쇼(아래 null을 허용하는 칼럼들도 마찬가지)

2024-09-30 03:41 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/entity/Product.java
> +    private int quantity;           // 포장 수량
앗 잘못달았다

2024-09-30 03:42 UTC, uzz99 commented on src/main/java/beyond/samdasoo/admin/entity/Product.java
> +    private int taxRate;            // 세율
이 부분입니다.........

2024-09-30 05:02 UTC, uzz99 approved these changes

2024-09-30 05:02 UTC, merged